# Generated by Django 4.1.4 on 2024-02-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animalid', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='static')),
                ('species', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(default='unknown', max_length=100)),
                ('contact', models.BigIntegerField(null=True)),
                ('availabilitystatus', models.BooleanField()),
                ('uploadedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
