# Generated by Django 4.1.4 on 2024-02-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
